name: Bench A11yWatch
on: [pull_request]

env:
  AI_DISABLED: true

jobs:
  run-container:
    name: Bench Website Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://a11ywatch.com
          SUBDOMAINS: true
          LIST: true
          SITEMAP: true
          FAIL_TOTAL_COUNT: 1
